apiVersion: v1
kind: Service
metadata:
  name: payflow-order-api
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-order-api
    app.kubernetes.io/part-of: payflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payflow-order-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: payflow-payment-api
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-payment-api
    app.kubernetes.io/part-of: payflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payflow-payment-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: payflow-mock-payment-provider
  namespace: payflow
  labels:
    app.kubernetes.io/name: payflow-mock-payment-provider
    app.kubernetes.io/part-of: payflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payflow-mock-payment-provider
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
