// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PayFlow.Payment.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PaymentDbContext))]
partial class PaymentDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.InboxMessageEntity",
            entity =>
            {
                entity.Property<string>("ConsumerName")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("consumer_name");

                entity.Property<Guid>("MessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("message_id");

                entity.Property<Guid>("AggregateId")
                    .HasColumnType("uuid")
                    .HasColumnName("aggregate_id");

                entity.Property<Guid?>("CausationId")
                    .HasColumnType("uuid")
                    .HasColumnName("causation_id");

                entity.Property<Guid>("CorrelationId")
                    .HasColumnType("uuid")
                    .HasColumnName("correlation_id");

                entity.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("message_type");

                entity.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_at_utc");

                entity.Property<DateTimeOffset?>("ProcessedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_at_utc");

                entity.Property<DateTimeOffset>("ReceivedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("received_at_utc");

                entity.Property<int>("SchemaVersion")
                    .HasColumnType("integer")
                    .HasColumnName("schema_version");

                entity.Property<long>("SourceOffset")
                    .HasColumnType("bigint")
                    .HasColumnName("source_offset");

                entity.Property<int>("SourcePartition")
                    .HasColumnType("integer")
                    .HasColumnName("source_partition");

                entity.Property<string>("SourceTopic")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("source_topic");

                entity.HasKey("ConsumerName", "MessageId");

                entity.HasIndex("ProcessedAtUtc");

                entity.HasIndex("SourceTopic", "SourcePartition", "SourceOffset")
                    .HasDatabaseName("IX_inbox_messages_source_position");

                entity.ToTable(
                    "inbox_messages",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inbox_messages_schema_version_positive",
                            "schema_version > 0");
                        table.HasCheckConstraint(
                            "ck_inbox_messages_source_partition_non_negative",
                            "source_partition >= 0");
                        table.HasCheckConstraint(
                            "ck_inbox_messages_source_offset_non_negative",
                            "source_offset >= 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.OutboxMessageEntity",
            entity =>
            {
                entity.Property<Guid>("OutboxMessageId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("outbox_message_id");

                entity.Property<Guid>("AggregateId")
                    .HasColumnType("uuid")
                    .HasColumnName("aggregate_id");

                entity.Property<int>("AttemptCount")
                    .ValueGeneratedOnAdd()
                    .HasDefaultValue(0)
                    .HasColumnType("integer")
                    .HasColumnName("attempt_count");

                entity.Property<Guid?>("CausationId")
                    .HasColumnType("uuid")
                    .HasColumnName("causation_id");

                entity.Property<DateTimeOffset?>("ClaimedUntilUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("claimed_until_utc");

                entity.Property<Guid?>("ClaimToken")
                    .HasColumnType("uuid")
                    .HasColumnName("claim_token");

                entity.Property<Guid>("CorrelationId")
                    .HasColumnType("uuid")
                    .HasColumnName("correlation_id");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                entity.Property<string>("Destination")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("destination");

                entity.Property<string>("LastErrorCode")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("last_error_code");

                entity.Property<Guid>("MessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("message_id");

                entity.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("message_type");

                entity.Property<DateTimeOffset?>("NextAttemptAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("next_attempt_at_utc");

                entity.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_at_utc");

                entity.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("payload");

                entity.Property<string>("Producer")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("producer");

                entity.Property<DateTimeOffset?>("PublishedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("published_at_utc");

                entity.Property<int>("SchemaVersion")
                    .HasColumnType("integer")
                    .HasColumnName("schema_version");

                entity.Property<string>("TraceParent")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("trace_parent");

                entity.HasKey("OutboxMessageId");

                entity.HasIndex("MessageId")
                    .IsUnique();

                entity.HasIndex("PublishedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc")
                    .HasDatabaseName("IX_outbox_messages_publish_pending")
                    .HasFilter("published_at_utc IS NULL");

                entity.ToTable(
                    "outbox_messages",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_outbox_messages_schema_version_positive",
                            "schema_version > 0");
                        table.HasCheckConstraint(
                            "ck_outbox_messages_attempt_count_non_negative",
                            "attempt_count >= 0");
                        table.HasCheckConstraint(
                            "ck_outbox_messages_claim_pair",
                            "(claim_token IS NULL AND claimed_until_utc IS NULL) OR (claim_token IS NOT NULL AND claimed_until_utc IS NOT NULL)");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.LedgerEntryEntity",
            entity =>
            {
                entity.Property<Guid>("LedgerEntryId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("ledger_entry_id");

                entity.Property<string>("AccountId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("account_id");

                entity.Property<decimal>("Amount")
                    .HasPrecision(19, 4)
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("amount");

                entity.Property<string>("Currency")
                    .IsRequired()
                    .IsFixedLength()
                    .HasMaxLength(3)
                    .HasColumnType("character(3)")
                    .HasColumnName("currency");

                entity.Property<Guid>("LedgerTransactionId")
                    .HasColumnType("uuid")
                    .HasColumnName("ledger_transaction_id");

                entity.Property<string>("Side")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("side");

                entity.HasKey("LedgerEntryId");

                entity.HasIndex("LedgerTransactionId");

                entity.ToTable(
                    "ledger_entries",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_ledger_entries_amount_positive",
                            "amount > 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.LedgerTransactionEntity",
            entity =>
            {
                entity.Property<Guid>("LedgerTransactionId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("ledger_transaction_id");

                entity.Property<Guid>("BusinessOperationId")
                    .HasColumnType("uuid")
                    .HasColumnName("business_operation_id");

                entity.Property<string>("Currency")
                    .IsRequired()
                    .IsFixedLength()
                    .HasMaxLength(3)
                    .HasColumnType("character(3)")
                    .HasColumnName("currency");

                entity.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_at_utc");

                entity.Property<string>("OperationType")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("operation_type");

                entity.HasKey("LedgerTransactionId");

                entity.HasIndex("OperationType", "BusinessOperationId")
                    .IsUnique()
                    .HasDatabaseName("IX_ledger_transactions_business_identity");

                entity.ToTable("ledger_transactions");
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.PaymentEntity",
            entity =>
            {
                entity.Property<Guid>("PaymentId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("payment_id");

                entity.Property<decimal>("Amount")
                    .HasPrecision(19, 4)
                    .HasColumnType("numeric(19,4)")
                    .HasColumnName("amount");

                entity.Property<DateTimeOffset?>("CapturedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("captured_at_utc");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                entity.Property<string>("Currency")
                    .IsRequired()
                    .IsFixedLength()
                    .HasMaxLength(3)
                    .HasColumnType("character(3)")
                    .HasColumnName("currency");

                entity.Property<string>("FailureReasonCode")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("failure_reason_code");

                entity.Property<Guid>("OrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("order_id");

                entity.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                entity.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                entity.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                entity.HasKey("PaymentId");

                entity.HasIndex("OrderId")
                    .HasDatabaseName("IX_payments_order_id");

                entity.ToTable(
                    "payments",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_payments_amount_positive",
                            "amount > 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.ProviderOperationEntity",
            entity =>
            {
                entity.Property<Guid>("ProviderOperationId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("provider_operation_id");

                entity.Property<int>("AttemptCount")
                    .HasColumnType("integer")
                    .HasColumnName("attempt_count");

                entity.Property<Guid>("BusinessOperationId")
                    .HasColumnType("uuid")
                    .HasColumnName("business_operation_id");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                entity.Property<string>("LastErrorCode")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("last_error_code");

                entity.Property<DateTimeOffset?>("LastAttemptAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_attempt_at_utc");

                entity.Property<DateTimeOffset?>("NextAttemptAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("next_attempt_at_utc");

                entity.Property<string>("OperationType")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("operation_type");

                entity.Property<string>("ProviderIdempotencyKey")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("provider_idempotency_key");

                entity.Property<string>("ProviderReference")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("provider_reference");

                entity.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                entity.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                entity.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                entity.HasKey("ProviderOperationId");

                entity.HasIndex("ProviderIdempotencyKey")
                    .IsUnique();

                entity.HasIndex("OperationType", "BusinessOperationId")
                    .IsUnique()
                    .HasDatabaseName("IX_provider_operations_business_identity");

                entity.HasIndex("Status", "NextAttemptAtUtc")
                    .HasDatabaseName("IX_provider_operations_reconciliation");

                entity.ToTable(
                    "provider_operations",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_provider_operations_attempt_count_non_negative",
                            "attempt_count >= 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.LedgerEntryEntity",
            entity =>
            {
                entity.HasOne(
                        "PayFlow.Payment.Infrastructure.Persistence.Entities.LedgerTransactionEntity",
                        "Transaction")
                    .WithMany("Entries")
                    .HasForeignKey("LedgerTransactionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                entity.Navigation("Transaction");
            });

        modelBuilder.Entity(
            "PayFlow.Payment.Infrastructure.Persistence.Entities.LedgerTransactionEntity",
            entity =>
            {
                entity.Navigation("Entries");
            });
#pragma warning restore 612, 618
    }
}
