// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayFlow.Inventory.Infrastructure.Persistence;

#nullable disable

namespace PayFlow.Inventory.Infrastructure.Persistence.Migrations;

[DbContext(typeof(InventoryDbContext))]
partial class InventoryDbContextModelSnapshot
    : ModelSnapshot
{
    protected override void BuildModel(
        ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation(
                "ProductVersion",
                "10.0.12")
            .HasAnnotation(
                "Relational:MaxIdentifierLength",
                63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(
            modelBuilder);

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InboxMessageEntity",
            entity =>
            {
                entity.Property<string>("ConsumerName")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("consumer_name");

                entity.Property<Guid>("MessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("message_id");

                entity.Property<Guid>("AggregateId")
                    .HasColumnType("uuid")
                    .HasColumnName("aggregate_id");

                entity.Property<Guid?>("CausationId")
                    .HasColumnType("uuid")
                    .HasColumnName("causation_id");

                entity.Property<Guid>("CorrelationId")
                    .HasColumnType("uuid")
                    .HasColumnName("correlation_id");

                entity.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("message_type");

                entity.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_at_utc");

                entity.Property<DateTimeOffset?>("ProcessedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_at_utc");

                entity.Property<DateTimeOffset>("ReceivedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("received_at_utc");

                entity.Property<int>("SchemaVersion")
                    .HasColumnType("integer")
                    .HasColumnName("schema_version");

                entity.Property<long>("SourceOffset")
                    .HasColumnType("bigint")
                    .HasColumnName("source_offset");

                entity.Property<int>("SourcePartition")
                    .HasColumnType("integer")
                    .HasColumnName("source_partition");

                entity.Property<string>("SourceTopic")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("source_topic");

                entity.HasKey("ConsumerName", "MessageId");

                entity.HasIndex("ProcessedAtUtc");

                entity.HasIndex("SourceTopic", "SourcePartition", "SourceOffset")
                    .HasDatabaseName("IX_inbox_messages_source_position");

                entity.ToTable(
                    "inbox_messages",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inbox_messages_schema_version_positive",
                            "schema_version > 0");

                        table.HasCheckConstraint(
                            "ck_inbox_messages_source_offset_non_negative",
                            "source_offset >= 0");

                        table.HasCheckConstraint(
                            "ck_inbox_messages_source_partition_non_negative",
                            "source_partition >= 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.OutboxMessageEntity",
            entity =>
            {
                entity.Property<Guid>("OutboxMessageId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("outbox_message_id");

                entity.Property<Guid>("AggregateId")
                    .HasColumnType("uuid")
                    .HasColumnName("aggregate_id");

                entity.Property<int>("AttemptCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0)
                    .HasColumnName("attempt_count");

                entity.Property<Guid?>("CausationId")
                    .HasColumnType("uuid")
                    .HasColumnName("causation_id");

                entity.Property<DateTimeOffset?>("ClaimedUntilUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("claimed_until_utc");

                entity.Property<Guid?>("ClaimToken")
                    .HasColumnType("uuid")
                    .HasColumnName("claim_token");

                entity.Property<Guid>("CorrelationId")
                    .HasColumnType("uuid")
                    .HasColumnName("correlation_id");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                entity.Property<string>("Destination")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("destination");

                entity.Property<string>("LastErrorCode")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("last_error_code");

                entity.Property<Guid>("MessageId")
                    .HasColumnType("uuid")
                    .HasColumnName("message_id");

                entity.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("message_type");

                entity.Property<DateTimeOffset?>("NextAttemptAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("next_attempt_at_utc");

                entity.Property<DateTimeOffset>("OccurredAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_at_utc");

                entity.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("payload");

                entity.Property<string>("Producer")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("producer");

                entity.Property<DateTimeOffset?>("PublishedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("published_at_utc");

                entity.Property<int>("SchemaVersion")
                    .HasColumnType("integer")
                    .HasColumnName("schema_version");

                entity.Property<string>("TraceParent")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("trace_parent");

                entity.HasKey("OutboxMessageId");

                entity.HasIndex("MessageId")
                    .IsUnique();

                entity.HasIndex("PublishedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc")
                    .HasDatabaseName("IX_outbox_messages_publish_pending")
                    .HasFilter("published_at_utc IS NULL");

                entity.ToTable(
                    "outbox_messages",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_outbox_messages_attempt_count_non_negative",
                            "attempt_count >= 0");

                        table.HasCheckConstraint(
                            "ck_outbox_messages_claim_pair",
                            "(claim_token IS NULL AND claimed_until_utc IS NULL) OR (claim_token IS NOT NULL AND claimed_until_utc IS NOT NULL)");

                        table.HasCheckConstraint(
                            "ck_outbox_messages_schema_version_positive",
                            "schema_version > 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationEntity",
            entity =>
            {
                entity.Property<Guid>("ReservationId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("reservation_id");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                entity.Property<DateTimeOffset>("ExpiresAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at_utc");

                entity.Property<Guid>("OrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("order_id");

                entity.Property<string>("RejectionReasonCode")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("rejection_reason_code");

                entity.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                entity.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                entity.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                entity.HasKey("ReservationId");

                entity.HasIndex("OrderId")
                    .HasDatabaseName(
                        "IX_inventory_reservations_order_id");

                entity.ToTable(
                    "inventory_reservations",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inventory_reservations_expiry_after_creation",
                            "expires_at_utc > created_at_utc");

                        table.HasCheckConstraint(
                            "ck_inventory_reservations_rejection_reason",
                            "(status = 'Rejected' AND rejection_reason_code IS NOT NULL) OR (status <> 'Rejected' AND rejection_reason_code IS NULL)");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.StockItemEntity",
            entity =>
            {
                entity.Property<string>("SkuId")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("sku_id");

                entity.Property<int>("OnHand")
                    .HasColumnType("integer")
                    .HasColumnName("on_hand");

                entity.Property<int>("Reserved")
                    .HasColumnType("integer")
                    .HasColumnName("reserved");

                entity.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                entity.HasKey("SkuId");

                entity.ToTable(
                    "inventory_stock",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inventory_stock_on_hand_non_negative",
                            "on_hand >= 0");

                        table.HasCheckConstraint(
                            "ck_inventory_stock_reserved_range",
                            "reserved >= 0 AND reserved <= on_hand");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationItemEntity",
            entity =>
            {
                entity.Property<Guid>("ReservationId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("reservation_id");

                entity.Property<int>("Position")
                    .ValueGeneratedNever()
                    .HasColumnType("integer")
                    .HasColumnName("position");

                entity.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                entity.Property<string>("SkuId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("sku_id");

                entity.HasKey(
                    "ReservationId",
                    "Position");

                entity.ToTable(
                    "inventory_reservation_items",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inventory_reservation_items_quantity_positive",
                            "quantity > 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationItemEntity",
            entity =>
            {
                entity.HasOne(
                        "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationEntity",
                        "Reservation")
                    .WithMany("Items")
                    .HasForeignKey("ReservationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                entity.Navigation("Reservation");
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationEntity",
            entity =>
            {
                entity.Navigation("Items");
            });
#pragma warning restore 612, 618
    }
}
