// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PayFlow.Inventory.Infrastructure.Persistence;

#nullable disable

namespace PayFlow.Inventory.Infrastructure.Persistence.Migrations;

[DbContext(typeof(InventoryDbContext))]
partial class InventoryDbContextModelSnapshot
    : ModelSnapshot
{
    protected override void BuildModel(
        ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation(
                "ProductVersion",
                "10.0.12")
            .HasAnnotation(
                "Relational:MaxIdentifierLength",
                63);

        Npgsql.EntityFrameworkCore.PostgreSQL.Metadata
            .NpgsqlModelBuilderExtensions
            .UseIdentityByDefaultColumns(
                modelBuilder);

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationEntity",
            entity =>
            {
                entity.Property<Guid>("ReservationId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("reservation_id");

                entity.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                entity.Property<DateTimeOffset>("ExpiresAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at_utc");

                entity.Property<Guid>("OrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("order_id");

                entity.Property<string>("RejectionReasonCode")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("rejection_reason_code");

                entity.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("status");

                entity.Property<DateTimeOffset>("UpdatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at_utc");

                entity.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                entity.HasKey("ReservationId");

                entity.HasIndex("OrderId")
                    .HasDatabaseName(
                        "IX_inventory_reservations_order_id");

                entity.ToTable(
                    "inventory_reservations",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inventory_reservations_expiry_after_creation",
                            "expires_at_utc > created_at_utc");

                        table.HasCheckConstraint(
                            "ck_inventory_reservations_rejection_reason",
                            "(status = 'Rejected' AND rejection_reason_code IS NOT NULL) OR (status <> 'Rejected' AND rejection_reason_code IS NULL)");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationItemEntity",
            entity =>
            {
                entity.Property<Guid>("ReservationId")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("reservation_id");

                entity.Property<int>("Position")
                    .ValueGeneratedNever()
                    .HasColumnType("integer")
                    .HasColumnName("position");

                entity.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                entity.Property<string>("SkuId")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("sku_id");

                entity.HasKey(
                    "ReservationId",
                    "Position");

                entity.ToTable(
                    "inventory_reservation_items",
                    table =>
                    {
                        table.HasCheckConstraint(
                            "ck_inventory_reservation_items_quantity_positive",
                            "quantity > 0");
                    });
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationItemEntity",
            entity =>
            {
                entity.HasOne(
                        "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationEntity",
                        "Reservation")
                    .WithMany("Items")
                    .HasForeignKey("ReservationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                entity.Navigation("Reservation");
            });

        modelBuilder.Entity(
            "PayFlow.Inventory.Infrastructure.Persistence.Entities.InventoryReservationEntity",
            entity =>
            {
                entity.Navigation("Items");
            });
#pragma warning restore 612, 618
    }
}
